// File generated by FlutterFire CLI.

// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.

///

/// Example:

/// ```dart

/// import 'firebase_options.dart';

/// // ...

/// await Firebase.initializeApp(

///   options: DefaultFirebaseOptions.currentPlatform,

/// );

/// ```

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {

    if (kIsWeb) {

      return web;

    }

    switch (defaultTargetPlatform) {

      case TargetPlatform.android:

        return android;

      case TargetPlatform.windows:

        return windows;

      default:

        throw UnsupportedError(

          'DefaultFirebaseOptions are not supported for this platform.',

        );

    }

  }



  static const FirebaseOptions web = FirebaseOptions(

    apiKey: 'AIzaSyBJcZ2AoUWd-2VsbHdMytm47ORujzO5OzE',

    appId: '1:736669163890:web:placeholder',

    messagingSenderId: '736669163890',

    projectId: 'studio-9839508681-122cf',

    authDomain: 'studio-9839508681-122cf.firebaseapp.com',

    storageBucket: 'studio-9839508681-122cf.firebasestorage.app',

  );



  static const FirebaseOptions android = FirebaseOptions(

    apiKey: 'AIzaSyBJcZ2AoUWd-2VsbHdMytm47ORujzO5OzE',

    appId: '1:736669163890:android:d83e9c813ed644f613fdeb',

    messagingSenderId: '736669163890',

    projectId: 'studio-9839508681-122cf',

    storageBucket: 'studio-9839508681-122cf.firebasestorage.app',

  );



  static const FirebaseOptions windows = FirebaseOptions(

    apiKey: 'AIzaSyBJcZ2AoUWd-2VsbHdMytm47ORujzO5OzE',

    appId: '1:736669163890:windows:placeholder',

    messagingSenderId: '736669163890',

    projectId: 'studio-9839508681-122cf',

    authDomain: 'studio-9839508681-122cf.firebaseapp.com',

    storageBucket: 'studio-9839508681-122cf.firebasestorage.app',

  );

}

